function make_gis_table_distribution(stat_combined,table_name,folder_out)


%% write table
[ta_b1, tab_names1] = tablenofun(stat_combined);
ta_b1.Properties.VariableNames  = tab_names1;

[ta_b2, tab_names2] = tablenofun_sieving(stat_combined);
ta_b2.Properties.VariableNames  = tab_names2;

cd(folder_out);  
writetable(ta_b1, table_name,  'Delimiter', '\t' );
writetable(ta_b2, [table_name,'_sieving'],  'Delimiter', '\t' );



%% sieving out
function [ta_b, tab_names] = tablenofun_sieving(stat_combined)

time_vec = datevec(stat_combined.timenumber'); % timestring quick
timestring = num2str(time_vec); year_nb = time_vec(:,1);
ID(:,1) = 1: length(stat_combined.timenumber);

ta_b = table(ID, stat_combined.timenumber', timestring, year_nb, stat_combined.projects', ...                   5
    stat_combined.samplename', stat_combined.XY(1,:)', stat_combined.XY(2,:)', ...                              3
    stat_combined.latlon(2,:)', stat_combined.latlon(1,:)' );                                 

tab_names = {'ID', 'timenumber', 'timestring', 'year', 'project', ...                                           5
             'samplename', 'X', 'Y',...                                                                         3
             'lat', 'lon', ['gs_1um_1um_',num2str(size(stat_combined.sieving,1)),'um'] };

ta_b = [ta_b , table(stat_combined.sieving') ];


%% grabs out
function [ta_b, tab_names] = tablenofun(stat_combined)

%% Time information
time_vec   = datevec(stat_combined.timenumber');
for p = 1:length(stat_combined.timenumber)
    try % quick workaround (somewhere messsy data (?))
        timestring(p,1) = cellstr(datestr(stat_combined.timenumber(p)'));
    catch
        timestring{p,1} = NaN;
    end
end
year_nb    = time_vec(:,1);

ID = (1:length(stat_combined.timenumber))';

%% Base table
ta_b = table( ...
    ID, ...
    stat_combined.timenumber', ...
    timestring, ...
    year_nb, ...
    stat_combined.projects', ...
    stat_combined.samplename', ...
    stat_combined.XY(1,:)', ...
    stat_combined.XY(2,:)', ...
    stat_combined.latlon(2,:)', ...
    stat_combined.latlon(1,:)', ...
    stat_combined.geo_mean', ...
    stat_combined.arit_mean', ...
    stat_combined.median', ...
    stat_combined.modestatus', ...
    stat_combined.mode_1', ...
    stat_combined.mode_2', ...
    stat_combined.mode_3', ...
    stat_combined.sorting_nb_FolkWard57', ...
    stat_combined.sorting_class_FolkWard57', ...
    stat_combined.sorting_num_stdev', ...
    stat_combined.sorting_num_McLaren', ...
    stat_combined.skewness_McLaren', ...
    stat_combined.sortMC_pos', ...
    stat_combined.skewMC_pos', ...
    stat_combined.skewness_matlab', ...
    stat_combined.sort_um', ...
    stat_combined.LevelA', ...
    stat_combined.LevelB', ...
    stat_combined.LevelC', ...
    stat_combined.sedmost', ...
    stat_combined.finematerial', ...
    stat_combined.justsand', ...
    stat_combined.justgravel', ...
    stat_combined.finesand', ...
    stat_combined.middlesand', ...
    stat_combined.coarsesand' ...
    );

%% Base variable names
tab_names = { ...
    'ID', ...
    'timenumber', ...
    'timestring', ...
    'year', ...
    'project', ...
    'samplename', ...
    'X', ...
    'Y', ...
    'lat', ...
    'lon', ...
    'geo_mean', ...
    'arit_mean', ...
    'median', ...
    'modestatus', ...
    'mode_1', ...
    'mode_2', ...
    'mode_3', ...
    'sortnum_FolkWard57', ...
    'sort_classFolkWard57', ...
    'sort_stdev', ...
    'sortnum_McLaren', ...
    'skew_McLaren', ...
    'sortMCpos', ...
    'skewMCpos', ...
    'skew_matlab', ...
    'sort_um', ...
    'LevelA', ...
    'LevelB', ...
    'LevelC', ...
    'Sedmost', ...
    'finematerial', ...
    'justsand', ...
    'justgravel', ...
    'finesand', ...
    'middlesand', ...
    'coarsesand' ...
    };


for k = 1:size(stat_combined.dis_percent,1) % gz dis add

    ta_b = addvars(ta_b, ...
        stat_combined.dis_percent(k,:)', ...
        'NewVariableNames', ...
        matlab.lang.makeValidName( ...
        ['um_' num2str(stat_combined.gz_classes(k,1))]), ...
        'After', width(ta_b));

    tab_names{end+1} = matlab.lang.makeValidName( ...
        ['um_' num2str(stat_combined.gz_classes(k,1))]);

end

ta_b.Properties.VariableNames = tab_names;




